### PR TITLE
add -C -A -B option ,function similar to grep

### PR DESCRIPTION
**Pull request by chenyuzhen**
add -C -A -B option ,function similar to grep

thx

chenyuzhen

### CODE REVIEW

**Comment by danielg4** [comment]
Hi. I previously submitted a PR on top of that:
https://github.com/maelnor/bgrep/pull/1

**Comment by xloem** [comment]
is this resolved?  could it be closed if so, so that visitors can understand the repository more easily?

**Comment by danielg4** [comment]
There are three competing patches, which must still be reconciled…

**Comment by tmbinc** [comment]
Thanks!

There's similar functionality in dump_context. While I like that this doesn't require lseek, it doesn't actually work if the search string is near the start of the buffer, i.e. near multiples of 1024-len(searchstring). Also, it changes the output format for the search results.

I'm favorable to a change that supports dumping context without lseek, but it would need to work in all cases. 

I'm closing this for now because the basic functionality is available, but if any improvements on the current strategy are desired, I'm happy to take them.

**Pull request closed without merging**
